spring:
  profiles: qa
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    password: Bearsfan580!
    url: jdbc:mysql://localhost:3306/datawebappDB
    username: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
welcome:
  message: Welcome!

management:
  endpoints:
    web:
      exposure:
        include: "*"
        exclude: "env,beans"

