server:
  port: 8082

spring:
  profiles:
    active: main
---
    spring:
      profiles: main

  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    password: ${SPRING_DATASOURCE_PASSWORD}
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

